import type { Formation } from "../types/game";

export const formations: Formation[] = [
  {
    id: "4-3-3",
    name: "4-3-3",
    focus: "attack",
    description: "Balanced shape with wide forwards and a midfield trio.",
    slots: [
      { id: "gk", label: "GK", line: "GK", x: 50, y: 6 },
      { id: "lb", label: "LB", line: "DEF", x: 16, y: 26 },
      { id: "cb1", label: "CB", line: "DEF", x: 38, y: 22 },
      { id: "cb2", label: "CB", line: "DEF", x: 62, y: 22 },
      { id: "rb", label: "RB", line: "DEF", x: 84, y: 26 },
      { id: "cm1", label: "CM", line: "MID", x: 30, y: 52 },
      { id: "cm2", label: "CM", line: "MID", x: 50, y: 48 },
      { id: "cm3", label: "CM", line: "MID", x: 70, y: 52 },
      { id: "lw", label: "LW", line: "FWD", x: 18, y: 80 },
      { id: "st", label: "ST", line: "FWD", x: 50, y: 86 },
      { id: "rw", label: "RW", line: "FWD", x: 82, y: 80 },
    ],
  },
  {
    id: "3-4-3",
    name: "3-4-3",
    focus: "attack",
    description: "Three at the back, wing-backs flying, front three running riot.",
    slots: [
      { id: "gk", label: "GK", line: "GK", x: 50, y: 6 },
      { id: "cb1", label: "CB", line: "DEF", x: 28, y: 22 },
      { id: "cb2", label: "CB", line: "DEF", x: 50, y: 20 },
      { id: "cb3", label: "CB", line: "DEF", x: 72, y: 22 },
      { id: "lm", label: "LM", line: "MID", x: 14, y: 52 },
      { id: "cm1", label: "CM", line: "MID", x: 38, y: 50 },
      { id: "cm2", label: "CM", line: "MID", x: 62, y: 50 },
      { id: "rm", label: "RM", line: "MID", x: 86, y: 52 },
      { id: "lw", label: "LW", line: "FWD", x: 22, y: 82 },
      { id: "st", label: "ST", line: "FWD", x: 50, y: 88 },
      { id: "rw", label: "RW", line: "FWD", x: 78, y: 82 },
    ],
  },
  {
    id: "4-4-2",
    name: "4-4-2",
    focus: "balanced",
    description: "Classic two banks of four behind a striker pairing.",
    slots: [
      { id: "gk", label: "GK", line: "GK", x: 50, y: 6 },
      { id: "lb", label: "LB", line: "DEF", x: 16, y: 26 },
      { id: "cb1", label: "CB", line: "DEF", x: 38, y: 22 },
      { id: "cb2", label: "CB", line: "DEF", x: 62, y: 22 },
      { id: "rb", label: "RB", line: "DEF", x: 84, y: 26 },
      { id: "lm", label: "LM", line: "MID", x: 16, y: 54 },
      { id: "cm1", label: "CM", line: "MID", x: 40, y: 50 },
      { id: "cm2", label: "CM", line: "MID", x: 60, y: 50 },
      { id: "rm", label: "RM", line: "MID", x: 84, y: 54 },
      { id: "st1", label: "ST", line: "FWD", x: 38, y: 84 },
      { id: "st2", label: "ST", line: "FWD", x: 62, y: 84 },
    ],
  },
  {
    id: "4-2-3-1",
    name: "4-2-3-1",
    focus: "attack",
    description: "Double pivot supporting an attacking band and lone striker.",
    slots: [
      { id: "gk", label: "GK", line: "GK", x: 50, y: 6 },
      { id: "lb", label: "LB", line: "DEF", x: 16, y: 26 },
      { id: "cb1", label: "CB", line: "DEF", x: 38, y: 22 },
      { id: "cb2", label: "CB", line: "DEF", x: 62, y: 22 },
      { id: "rb", label: "RB", line: "DEF", x: 84, y: 26 },
      { id: "dm1", label: "DM", line: "MID", x: 38, y: 44 },
      { id: "dm2", label: "DM", line: "MID", x: 62, y: 44 },
      { id: "lam", label: "LAM", line: "MID", x: 20, y: 66 },
      { id: "cam", label: "CAM", line: "MID", x: 50, y: 68 },
      { id: "ram", label: "RAM", line: "MID", x: 80, y: 66 },
      { id: "st", label: "ST", line: "FWD", x: 50, y: 88 },
    ],
  },
  {
    id: "4-1-4-1",
    name: "4-1-4-1",
    focus: "midfield",
    description: "Anchor man shielding a flat four across the middle.",
    slots: [
      { id: "gk", label: "GK", line: "GK", x: 50, y: 6 },
      { id: "lb", label: "LB", line: "DEF", x: 16, y: 26 },
      { id: "cb1", label: "CB", line: "DEF", x: 38, y: 22 },
      { id: "cb2", label: "CB", line: "DEF", x: 62, y: 22 },
      { id: "rb", label: "RB", line: "DEF", x: 84, y: 26 },
      { id: "dm", label: "DM", line: "MID", x: 50, y: 42 },
      { id: "lm", label: "LM", line: "MID", x: 16, y: 58 },
      { id: "cm1", label: "CM", line: "MID", x: 38, y: 54 },
      { id: "cm2", label: "CM", line: "MID", x: 62, y: 54 },
      { id: "rm", label: "RM", line: "MID", x: 84, y: 58 },
      { id: "st", label: "ST", line: "FWD", x: 50, y: 86 },
    ],
  },
  {
    id: "4-3-2-1",
    name: "4-3-2-1",
    focus: "midfield",
    description: "Christmas tree — narrow tens feeding a lone finisher.",
    slots: [
      { id: "gk", label: "GK", line: "GK", x: 50, y: 6 },
      { id: "lb", label: "LB", line: "DEF", x: 16, y: 26 },
      { id: "cb1", label: "CB", line: "DEF", x: 38, y: 22 },
      { id: "cb2", label: "CB", line: "DEF", x: 62, y: 22 },
      { id: "rb", label: "RB", line: "DEF", x: 84, y: 26 },
      { id: "cm1", label: "CM", line: "MID", x: 30, y: 46 },
      { id: "cm2", label: "CM", line: "MID", x: 50, y: 44 },
      { id: "cm3", label: "CM", line: "MID", x: 70, y: 46 },
      { id: "am1", label: "AM", line: "MID", x: 35, y: 68 },
      { id: "am2", label: "AM", line: "MID", x: 65, y: 68 },
      { id: "st", label: "ST", line: "FWD", x: 50, y: 88 },
    ],
  },
  {
    id: "3-4-2-1",
    name: "3-4-2-1",
    focus: "attack",
    description: "Wing-backs and two no.10s supporting a central striker.",
    slots: [
      { id: "gk", label: "GK", line: "GK", x: 50, y: 6 },
      { id: "cb1", label: "CB", line: "DEF", x: 28, y: 22 },
      { id: "cb2", label: "CB", line: "DEF", x: 50, y: 20 },
      { id: "cb3", label: "CB", line: "DEF", x: 72, y: 22 },
      { id: "lm", label: "LM", line: "MID", x: 14, y: 50 },
      { id: "cm1", label: "CM", line: "MID", x: 38, y: 52 },
      { id: "cm2", label: "CM", line: "MID", x: 62, y: 52 },
      { id: "rm", label: "RM", line: "MID", x: 86, y: 50 },
      { id: "am1", label: "AM", line: "MID", x: 32, y: 72 },
      { id: "am2", label: "AM", line: "MID", x: 68, y: 72 },
      { id: "st", label: "ST", line: "FWD", x: 50, y: 88 },
    ],
  },
  {
    id: "3-5-2",
    name: "3-5-2",
    focus: "midfield",
    description: "Three at the back with wing-backs and a packed midfield.",
    slots: [
      { id: "gk", label: "GK", line: "GK", x: 50, y: 6 },
      { id: "cb1", label: "CB", line: "DEF", x: 28, y: 22 },
      { id: "cb2", label: "CB", line: "DEF", x: 50, y: 20 },
      { id: "cb3", label: "CB", line: "DEF", x: 72, y: 22 },
      { id: "lwb", label: "LWB", line: "MID", x: 12, y: 50 },
      { id: "cm1", label: "CM", line: "MID", x: 36, y: 52 },
      { id: "cm2", label: "CM", line: "MID", x: 50, y: 48 },
      { id: "cm3", label: "CM", line: "MID", x: 64, y: 52 },
      { id: "rwb", label: "RWB", line: "MID", x: 88, y: 50 },
      { id: "st1", label: "ST", line: "FWD", x: 38, y: 84 },
      { id: "st2", label: "ST", line: "FWD", x: 62, y: 84 },
    ],
  },
  {
    id: "4-5-1",
    name: "4-5-1",
    focus: "defence",
    description: "Five across midfield, soak up pressure, hit on the break.",
    slots: [
      { id: "gk", label: "GK", line: "GK", x: 50, y: 6 },
      { id: "lb", label: "LB", line: "DEF", x: 16, y: 26 },
      { id: "cb1", label: "CB", line: "DEF", x: 38, y: 22 },
      { id: "cb2", label: "CB", line: "DEF", x: 62, y: 22 },
      { id: "rb", label: "RB", line: "DEF", x: 84, y: 26 },
      { id: "lm", label: "LM", line: "MID", x: 14, y: 54 },
      { id: "cm1", label: "CM", line: "MID", x: 32, y: 50 },
      { id: "cm2", label: "CM", line: "MID", x: 50, y: 48 },
      { id: "cm3", label: "CM", line: "MID", x: 68, y: 50 },
      { id: "rm", label: "RM", line: "MID", x: 86, y: 54 },
      { id: "st", label: "ST", line: "FWD", x: 50, y: 86 },
    ],
  },
  {
    id: "5-3-2",
    name: "5-3-2",
    focus: "defence",
    description: "Defensive five-at-the-back with a compact midfield three.",
    slots: [
      { id: "gk", label: "GK", line: "GK", x: 50, y: 6 },
      { id: "lwb", label: "LWB", line: "DEF", x: 12, y: 30 },
      { id: "cb1", label: "CB", line: "DEF", x: 32, y: 22 },
      { id: "cb2", label: "CB", line: "DEF", x: 50, y: 20 },
      { id: "cb3", label: "CB", line: "DEF", x: 68, y: 22 },
      { id: "rwb", label: "RWB", line: "DEF", x: 88, y: 30 },
      { id: "cm1", label: "CM", line: "MID", x: 30, y: 54 },
      { id: "cm2", label: "CM", line: "MID", x: 50, y: 50 },
      { id: "cm3", label: "CM", line: "MID", x: 70, y: 54 },
      { id: "st1", label: "ST", line: "FWD", x: 38, y: 84 },
      { id: "st2", label: "ST", line: "FWD", x: 62, y: 84 },
    ],
  },
];

export function getFormationById(id: string): Formation | undefined {
  return formations.find((formation) => formation.id === id);
}
